name: Deploy

on:
  workflow_run:
    workflows:
      - Test
    branches:
      - main
      - develop
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set BRANCH_TAG
        uses: nimblehq/branch-tag-action@v1.2
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Set HEROKU_APP_NAME
        run: |
          if [[ $BRANCH_TAG = "latest" ]]
          then
            echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME_PRODUCTION }}" >> $GITHUB_ENV
          else
            echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME_STAGING }}" >> $GITHUB_ENV
          fi


      - name: Log in to Heroku container
        run: heroku container:login

      - name: Publish application
        run: |
          heroku container:push web worker --recursive --app $HEROKU_APP_NAME
          heroku container:release web worker --app $HEROKU_APP_NAME
