name: Test

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Create .env file
        run: cp ".env.test" ".env"

      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51

      - name: Install dependencies
        run: make install-dependencies

      - name: Run tests
        run: make test
